kind: pipeline
type: docker
steps:
- name: Django
  image: python:3.10
  commands:
    - /usr/local/bin/python -m pip install --upgrade pip
    - pip install -r requirements.txt
    - python3 manage.py test

trigger:
  branch:
  - master