name: Django CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.9]

    steps:
    
    - uses: easingthemes/ssh-deploy@v2.0.7
    - name: Deploy 
    
      env:
          SSH_PRIVATE_KEY: ${{ secrets.ACCESS_TOKEN }}
          REMOTE_HOST: 47.115.204.166
      run: ls
