name: Django CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.9]

    steps:
    
    - name: Login to DockerHub
      if: GitHub.event_name != 'pull_request'
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - uses: actions/checkout@v3
    - name: Set up Python 3.9
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Tests
      run: |
        python manage.py test

    - uses: actions/checkout@v3
    - name: Docker-build
      run: docker build . --file Dockerfile --tag rainbow12/cdci
      
    - name: Docker-push
      run: docker push rainbow12/cdci

    - name: Deploy to server
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SERVER_IP }}
        username: ${{ secrets.SERVER_USER }}
        password: ${{ secrets.SERVER_PASSWD }}
        port: ${{ secrets.SERVER_PORT }}
        script: |
          docker rm -f Test_cdci
          docker rmi -f rainbow12/cdci
          cd /home/
          ls
          docker run -itd -p 1000:8000 --name Test_cdci rainbow12/cdci /bin/bash start.sh
